const BAR_WIDTH = 250;
const BAR_HEIGHT = 55;
const EMOJI_SIZE = 24;
const EMOJI_TRANSLATE_Y = BAR_HEIGHT * 2;
const DURATION = 1000;
const EMOJI_SPACING = 45;
const DISMISS_DURATION = 300;
export {
  BAR_WIDTH,
  BAR_HEIGHT,
  EMOJI_SIZE,
  EMOJI_TRANSLATE_Y,
  DURATION,
  EMOJI_SPACING,
  DISMISS_DURATION,
};
