const imagePath = "../../assets/list";

const listData = [
  {
    id: 1,
    title: "Amazon",
    subTitle: "Groceries",
    category: "Main Account",
    image: require(`${imagePath}/amazon.png`),
    price: -100,
  },
  {
    id: 2,
    title: "Lidl Wesseling",
    subTitle: "Groceries",
    category: "Main Account",
    image: require(`${imagePath}/lidl.png`),
    price: -85,
  },
  {
    id: 3,
    title: "Google",
    subTitle: "Salary",
    category: "Salary",
    image: require(`${imagePath}/google.png`),
    price: 3500,
  },
  {
    id: 4,
    title: "Apple",
    subTitle: "Electronics",
    category: "Main Account",
    image: require(`${imagePath}/apple.png`),
    price: -200,
  },
  {
    id: 5,
    title: "Dribbble",
    subTitle: "Design",
    category: "Subscription",
    image: require(`${imagePath}/dribble.png`),
    price: -50,
  },
  {
    id: 6,
    title: "GitHub",
    subTitle: "Code",
    category: "Main Account",
    image: require(`${imagePath}/github.png`),
    price: -75,
  },
  {
    id: 7,
    title: "Instagram",
    subTitle: "Social Media",
    category: "Main Account",
    image: require(`${imagePath}/instagram.png`),
    price: -150,
  },
  {
    id: 8,
    title: "Figma",
    subTitle: "Design Tool",
    category: "Main Account",
    image: require(`${imagePath}/figma.png`),
    price: -120,
  },
  {
    id: 9,
    title: "Twitter",
    subTitle: "Social Media",
    category: "Main Account",
    image: require(`${imagePath}/twitter.png`),
    price: -90,
  },
  {
    id: 10,
    title: "Spotify",
    subTitle: "Music Streaming",
    category: "Main Account",
    image: require(`${imagePath}/spotify.png`),
    price: 60,
  },
  {
    id: 11,
    title: "Netflix",
    subTitle: "Video Streaming",
    category: "Main Account",
    image: require(`${imagePath}/netflix.png`),
    price: 80,
  },
  {
    id: 12,
    title: "Dropbox",
    subTitle: "Cloud Storage",
    category: "Main Account",
    image: require(`${imagePath}/dropbox.png`),
    price: 55,
  },
];

export { listData };
