const MAX_PULL = 50;
const OPEN_THRESHOLD = 20;
const OPEN_VELOCITY = 700;
const SEARCH_HORIZONTAL_PADDING = 20;
const SEARCH_COLLAPSED_SIZE = 110;
const SEARCH_INPUT_COLLAPSED_HEIGHT = 40;
const SEARCH_INPUT_EXPANDED_HEIGHT = 50;
const MAX_BLUR_RADIUS = 30;
const springConfig = {
  damping: 18,
  stiffness: 180,
  mass: 0.6,
};
export {
  MAX_BLUR_RADIUS,
  MAX_PULL,
  OPEN_THRESHOLD,
  OPEN_VELOCITY,
  SEARCH_COLLAPSED_SIZE,
  SEARCH_HORIZONTAL_PADDING,
  SEARCH_INPUT_COLLAPSED_HEIGHT,
  SEARCH_INPUT_EXPANDED_HEIGHT,
  springConfig,
};
